apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: <ROLE_NAME>
rules:
- apiGroups:
  - cluster.k8s.io
  resources:
  - clusters
  - machines
  - machinesets
  - machinedeployments
  verbs:
  - "*"
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - secrets
  - services
  - endpoints
  - configmaps
  - persistentvolumeclaims
  - events
  - nodes
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - "*"
