language: generic
sudo: required
dist: trusty
services:
- docker
env:
  global:
  - secure: clkw/QvANjUKXvHSfvduHOg8NCl/1+3f5B0U+8xDc2eyWeQgQEySPX3Afz37TwKQK7JT3KDErZSX9y6BJrrSL3vfHmo3D9xSaCzrGyXEwkm/xUk+dgdkgpNXlz5H5re6GEnOYvAhSq+KOYjACSBWdcu3Xm12+OydwzcvDWLHopgQVWePkh7b3JP5dzbsOkx6QBYhWv55e1dMsvoaHWBeHjahaA0DZe/08iJDoSR0jIzHYmMgSHaKk3GJZO+00+cksge2kb+OAfxp+9MT5a/bfLYT0qQLtoliOj4IEpVkY1qXAaeYoKXgIQlZgGaP1tlxXO3ndqU371KxIXFOvzQSk4dBXPsuZahCSQThUAmLyHr0Egs1Tp0iEh2enZBtJcmThP/rQISRuAwTD/pNNLzGZIjjdvYzAAXR4GJ5T5ud9Tn2r8lXttSSlRkmgm6V4kmGI8AEWxxCPabQEM0XZZyT784a8A9p9zki4ndKBzlnAHyvg/UNhA8maphoU6N0v+cyXfT1T10t9FXDUKAqmJ20AqkRvbIXIhPOv1lgnOvm6s09u4FElvafyqURquHqrpDfdzo4r9zYu8ClIIxV5gWopTLdX1JoCW26jWx+AvPl6PDJSG8WlNtfdqIZ0JqozgZadhEkJtIMLaHa+fAeBqLIMylTUIn9yt2k3kwjGRC+SWk=
  - secure: DRquIPkm5FzUzqKgdE7bJUVuBXvOFPRztSEFbSSEB6LseHvY79HngB9Ph4RoCWRiZtEJFNJH5d2TwP+AY+UgKZeEIg7VtAWaoQ/VfEFEHp8FEWD6gxZf2z6Kt/p8iL/vEAe5EJjNwnN2XLsDySUHgXGng6k1fe0n9F7FOzzd71foItOZP0vpGVvCglWrjlgtIhKbhQqUorI686Zs9pL3wK7oj2gS74BbzJwixswt+OuWRTsn/t+VUr8bFZ1Uykt8xAnM+KE0ULPc0/+LXoJMImQo5jbGzcNUo3YBVNt+SFyluHIT9RekFIASwNuLytxi8Niw8B8kQsQM4KYV/jURhUoMc0uz6DBewku8mEGtOxFc2dUqmst6UHJyckvYElPRDDOiSdcW95XlqfK4qggZ3ckx6yR+cP7LPfNss1IACZkeZXBaFQpTm5P17FGoMdBAzAPcxw2wMLWyH9Xf/Xpi2V2pjgdFgsh4OIr8FfsIdla9ckEndvh6ODfScoFcVhACq7A/8IyWcr1dYrmju6iO7eoXvAtoTn6SlDZhocmhOMgZlchRh8ovyQBFWJdsq5vurr+wRagMVhAPpwrG/QnpAEDycZNYGMbTX6tW91hv3lS6f1MH4zrvvk9o1dvTBubSdxxTKJA/ICQuyhP6+Tv1Uan5ccmq71eY/GAxlgwSUwc=
install:
- git reset --hard
script:
- make bazel-generate
- if [[ -n "$(git status --porcelain)" ]] ; then echo "It seems like you need to run
  `make bazel-generate`. Please run it and commit the changes"; git status --porcelain;
  false; fi
- CONTAINER_TAG=$TRAVIS_TAG make bazel-generate-manifests-release
deploy:
- provider: script
  script: hack/dockerized "docker login -u=${DOCKER_USER} -p=${DOCKER_PASSWORD}" &&
    CONTAINER_TAG=latest make bazel-push-images-release
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: hack/dockerized "docker login -u=${$DOCKER_USER} -p=${$DOCKER_PASSWORD}"
    && CONTAINER_TAG=$TRAVIS_TAG make bazel-push-images-release
  skip_cleanup: true
  on:
    tags: true
- provider: releases
  skip_cleanup: true
  api_key:
    secure: HfTOaydOlOoZJH6zrRkaBoMRRi6T/qQ48LZOvgYOVVxrY65RJxcJGPIWuSHmTaG4gVnbvZX10X45hb3wdjNHQVAT/fJ4K5+7FFShdSF25bXgYgATJPvXwd4P9efq+4SL9z22NsEDc0vB3f354e5OMcT3USmV9Mp/u5wBporar01JEOeyb9P+PUYJkSZvlOIu3VI0FKEFIxjtaJjBEsbHNJAly+Ccdlpja/vViNxOB6jcq6EvhQZI95BnqSnTt89wG4veRr5L1EGse76FujA69RXvbXnZ3Aq8OdiIMtxXqg4N+jkQWtT2M6SkH6MbKTqW9mRfSIRmYFLhZH+PC429PpHxKGHc/JoVR61H8gy8IxAybNLQtRLIVPZ9pZNrOiLJXDr6TInyWGbYOnGev1FYslSEqllDKzF04b+lBpuzBzfvDj9yzoDo1dqZSAh4SnXtLWx+ML9zldPGEqoDltRdBXEmd72Zn46fApXfQ0N2knHMQPGBJ0kuQTwLl2fjkkV2SwIZrxMaQa/3FrNykkz0iwMwA7MsZmhNMqbMO/IkFUqylWZctfodjPfXuviUfe3Ff5jjbsu7BFexYOVmgLP8fibLpXxGGqwe8Qe748UPhslgPgkqLvPtlTcAa9i1PFPlybEBHY19+STElkl60Qkzo5ftd3rRs66x+oiUOkZCM2Q=
  file: _out/manifests/cluster-api-provider-external.yaml
  prerelease: true
  overwrite: true
  name: "$TRAVIS_TAG"
  on:
    repo: kubevirt/cluster-api-provider-external
    tags: true
