---
apiVersion: "cluster.k8s.io/v1alpha1"
kind: Cluster
metadata:
  name: example-cluster
  namespace: clusterapi-external-provider
  labels:
    kubevirt.io: "clusterapi-external-provider"
spec:
    providerConfig:
      value:
        apiVersion: "externalproviderconfig/v1alpha1"
        kind: "ExternalClusterProviderConfig"
        project: "example"