##############################################################################
## Discover a machine's power status with IPMI
##############################################################################

- name: Determin machine power state
  command: "/sbin/fence_{{ agent_type }} -P --ip {{ server }} --ipport {{ ipport }} --username {{ username }} --password {{ password }} -o status"
