##############################################################################
## Power on an machine with IPMI
##############################################################################

- name: Power on machine
  command: "/sbin/fence_{{ agent_type }} -P --ip {{ server }} --ipport {{ ipport }} --username {{ username }} --password {{ password }} -o on"