---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: cluster-api-external-provider
  labels:
    kubevirt.io: "cluster-api-external-provider"
rules:
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - update
      - create
      - patch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
      - update
      - delete
      - list
      - watch
      - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-api-external-provider
  labels:
    kubevirt.io: "cluster-api-external-provider"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cluster-api-external-provider
  labels:
    kubevirt.io: "cluster-api-external-provider"
roleRef:
  kind: ClusterRole
  name: cluster-api-external-provider
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: cluster-api-external-provider
