---
apiVersion: v1
kind: ConfigMap
metadata:
  name: machine-setup
data:
  machine_setup_configs.yaml: |-
    items:
    - machineParams:
      - label: ipmilan-machine
        roles:
        - worker
      config:
        startupScript: |
          set -ex
          (
          echo done.
          ) 2>&1 | tee /var/log/startup.log
        fencingConfig:
          name: had-drac
          container:
            name: fence-agents
            image: quay.io/beekhof/fence-agents:0.0.11
            command: [ "/bin/secret-handler.sh", "/sbin/fence_ipmilan", "-v" ]
          checkArgs:  [ "-o", "status" ]
          createArgs: [ "-o", "on"  ]
          deleteArgs: [ "-o", "off" ]
          argumentFormat: cli
          passTargetAs: port
          secrets:	
            username: ipmi-secret	
            password: ipmi-secret
